# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rpn < Formula
  desc "A Linux CLI RPN calculator"
  homepage "https://github.com/marcopaganini/rpn"
  version "1.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/marcopaganini/rpn/releases/download/v1.0.3/rpn_1.0.3_darwin_amd64.tar.gz"
      sha256 "0793099a818bf5477962ba98ec59aa25aeff559f0815716ca4dd91a1f2941254"

      define_method(:install) do
        bin.install "rpn"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/marcopaganini/rpn/releases/download/v1.0.3/rpn_1.0.3_darwin_arm64.tar.gz"
      sha256 "69d23bc5c957d89d554890f8293269a26204e4611e718f4b7e1c4feb247d14c4"

      define_method(:install) do
        bin.install "rpn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/marcopaganini/rpn/releases/download/v1.0.3/rpn_1.0.3_linux_amd64.tar.gz"
      sha256 "a2a8c6712465bd710ba914da48ea2b06205a7ecf49df66b610f9bb9befd73d17"
      define_method(:install) do
        bin.install "rpn"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/marcopaganini/rpn/releases/download/v1.0.3/rpn_1.0.3_linux_arm64.tar.gz"
      sha256 "a7962a25ede5abcb278b90c641849d191e7cb7cc37276ededbb95ccea6454440"
      define_method(:install) do
        bin.install "rpn"
      end
    end
  end
end
