# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rpn < Formula
  desc "A Linux CLI RPN calculator"
  homepage "https://github.com/marcopaganini/rpn"
  version "1.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/marcopaganini/rpn/releases/download/v1.0.2/rpn_1.0.2_darwin_amd64.tar.gz"
      sha256 "bc7a77944630fc3ebcb340d0575a898be4ed19069d2a94c9352d1901d117cb79"

      def install
        bin.install "rpn"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/marcopaganini/rpn/releases/download/v1.0.2/rpn_1.0.2_darwin_arm64.tar.gz"
      sha256 "aeb1c72677d21034a2cc824a96a1328c4cc0bbc644e718bc161f388e2582b638"

      def install
        bin.install "rpn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/marcopaganini/rpn/releases/download/v1.0.2/rpn_1.0.2_linux_amd64.tar.gz"
      sha256 "8d48f78360c2da43e25af1e47d02f319e90cd236c8c5df2fe75a9adff3eedfb3"
      def install
        bin.install "rpn"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/marcopaganini/rpn/releases/download/v1.0.2/rpn_1.0.2_linux_arm64.tar.gz"
      sha256 "bae6eb84989b205f51f225133dd0c678941a05918d59f210ece1a6fe3eb673c4"
      def install
        bin.install "rpn"
      end
    end
  end
end
