# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Videofix < Formula
  desc "Remove/transcode unwanted audio and subtitle tracks of your MKV files."
  homepage "https://github.com/marcopaganini/videofix"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/marcopaganini/videofix/releases/download/v0.1.1/videofix_0.1.1_darwin_amd64.tar.gz"
      sha256 "5820fa08a2cb525b9c4b6979a007034d8ac08742db742c1aa5afe1bfc618a87b"

      def install
        bin.install "videofix"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/marcopaganini/videofix/releases/download/v0.1.1/videofix_0.1.1_darwin_arm64.tar.gz"
      sha256 "84139fc929acbf0e6b76f2eed21983f3399d5b08c72f65a819358755d59bde4e"

      def install
        bin.install "videofix"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/marcopaganini/videofix/releases/download/v0.1.1/videofix_0.1.1_linux_amd64.tar.gz"
      sha256 "a5ae6c66b6c04b8bdb5188affac642ae409d96a9d7033a3dc7bdc976a58649f6"
      def install
        bin.install "videofix"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/marcopaganini/videofix/releases/download/v0.1.1/videofix_0.1.1_linux_arm64.tar.gz"
      sha256 "3f2e517c8f7cab019aedcdaa6fecf005376383679dbf820f2b43e05c80343452"
      def install
        bin.install "videofix"
      end
    end
  end
end
