# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Videofix < Formula
  desc "Remove/transcode unwanted audio and subtitle tracks of your MKV files."
  homepage "https://github.com/marcopaganini/videofix"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/marcopaganini/videofix/releases/download/v0.1.1/videofix_0.1.1_darwin_amd64.tar.gz"
      sha256 "da1057ee1e20ee8d99bb3dc069a71be965ae47c8b9ae7f0ea5d39bd08bbf952c"

      def install
        bin.install "videofix"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/marcopaganini/videofix/releases/download/v0.1.1/videofix_0.1.1_darwin_arm64.tar.gz"
      sha256 "6700b8f5578aa2809999da91f7d8137fe78cec5d79e4504e5ffd26e84a04f4b3"

      def install
        bin.install "videofix"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/marcopaganini/videofix/releases/download/v0.1.1/videofix_0.1.1_linux_amd64.tar.gz"
      sha256 "53fe7abb6b539679a4028dea542c2f0a45fad10116ec7ed4facd3c199df3de7d"
      def install
        bin.install "videofix"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/marcopaganini/videofix/releases/download/v0.1.1/videofix_0.1.1_linux_arm64.tar.gz"
      sha256 "3e0f4e8471376ed3ba2c78b7b64577c768aface41f3e5c678fcc58c43f93b16b"
      def install
        bin.install "videofix"
      end
    end
  end
end
