# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Videofix < Formula
  desc "Remove/transcode unwanted audio and subtitle tracks of your MKV files."
  homepage "https://github.com/marcopaganini/videofix"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/marcopaganini/videofix/releases/download/v0.1.1/videofix_0.1.1_darwin_amd64.tar.gz"
      sha256 "8f4283103886f1571840f6d5c4ab86b42e27e85c48e31e59c842bffdf53f0217"

      def install
        bin.install "videofix"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/marcopaganini/videofix/releases/download/v0.1.1/videofix_0.1.1_darwin_arm64.tar.gz"
      sha256 "266717d57b8d1d98bbf8ee63bf9536c53bd45acd9161d6c95abac991aa2f0d64"

      def install
        bin.install "videofix"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/marcopaganini/videofix/releases/download/v0.1.1/videofix_0.1.1_linux_amd64.tar.gz"
      sha256 "f8e9f8a2508f232e8c32a7a567e7bfaefe223fd9eb6dad13ede4177ba3651742"
      def install
        bin.install "videofix"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/marcopaganini/videofix/releases/download/v0.1.1/videofix_0.1.1_linux_arm64.tar.gz"
      sha256 "4a5ce2511f02c30398403d22da9491c5249da502e60fea6a7bd0ebcc581d316f"
      def install
        bin.install "videofix"
      end
    end
  end
end
